name: "[Admin] Add issue to milestone"

env:
    GH_TOKEN: ${{ github.token }}

on:
    pull_request:
      types:
        - closed
jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
          issues: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Store linked issues
              uses: nearform-actions/github-action-check-linked-issues@v1
              id: check-linked-issues
              with:
                exclude-branches: "release/**, dependabot/**, main, release-v**"
 
            - name: Update milestone
              if: ${{ steps.check-linked-issues.outputs.linked_issues_count }} > 1
              run: |
                thing=${{steps.check-linked-issues.outputs.issues}} 
                echo "thing: $thing[0]"
                echo value=${thing#*#}
                value=${value%"]"}
                gh issue edit $value --milestone v1.1.0
