name: "[Admin] Add issue to milestone"

env:
    GH_TOKEN: ${{ github.token }}

on:
    pull_request:
      types:
        - closed
jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
          issues: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Find linked issues
              id: find-linked-issues
              uses: Ismoh-Games/find-linked-issues@v1.0.6
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                repository: ${{ github.repository }}
                pull-request-number: ${{ github.event.pull_request.number }}
                pull-request-body: ${{ github.event.pull_request.body }}
                copy-issues-labels: true # optional
                include-closed-issues: true # optional

            # Use the output from the `find-linked-issues` step
            # gh issue edit 5 --milestone v1.1.0
            - name: Use the output
              run: |
                echo "is-pull-request-linked-to-issues: ${{ steps.find-linked-issues.outputs.is-pull-request-linked-to-issues }}"
                echo "linked-issues: ${{ steps.find-linked-issues.outputs.linked-issues }}"
                echo "pull-request-labels: ${{ steps.find-linked-issues.outputs.pull-request-labels }}"

            - name: Conditional step
              if: ${{ steps.find-linked-issues.outputs.is-pull-request-linked-to-issues == 'True' }}
              run: |
                echo "Pull request is linked to issues"

            - name: Another conditional step
              if: ${{ steps.find-linked-issues.outputs.is-pull-request-linked-to-issues == 'False' }}
              run: |
                exit 1

