name: "[Admin] Add issue to milestone"

env:
    GH_TOKEN: ${{ github.token }}

on:
    pull_request:
      types:
        - closed
jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
          issues: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Store linked issues
              uses: nearform-actions/github-action-check-linked-issues@v1
              id: check-linked-issues
              with:
                exclude-branches: "release/**, dependabot/**, main, release-v**"
 
            - name: Update milestone
              if: ${{ steps.check-linked-issues.outputs.linked_issues_count }} > 1
              run: |
                thing=${{steps.check-linked-issues.outputs.issues}} 
                echo "thing: $thing"
                  for i in $( $thing ); do
                    gh issue edit 13 --milestone v1.1.0
                    value=${i#*#}
                    echo "value: $value"
                    echo "value: $value" >> $GITHUB_ENV
                    echo "value: $value" >> $GITHUB_OUTPUT
                    echo $i
                  done
