name: "[Admin] Add issue to milestone"
on:
    pull_request:
      types:
        - closed
jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: nearform-actions/github-action-check-linked-issues@v1
              id: check-linked-issues
              with:
                exclude-branches: "release/**, dependabot/**, main, release-v**"
 
            - name: Get issue count
              if: ${{ steps.check-linked-issues.outputs.linked_issues_count }} > 1
              run: |
                echo ${{ steps.check-linked-issues.outputs.issues }}
                gh issue edit 5 --milestone v1.1.0
