name: "[Admin] Check for linked issues in PRs"
on:
    pull_request:
      types: [opened, edited, reopened, synchronize]

jobs:
    check_pull_requests:
        runs-on: ubuntu-latest
        name: Check linked issues
        permissions:
            issues: read
            pull-requests: write
        steps:
            - uses: nearform-actions/github-action-check-linked-issues@v1
              id: check-linked-issues
              with:
                exclude-branches: "release/**, dependabot/**"
                custom-body-comment: "${{ github.event.pull_request.user.login }} Please link this pull request to an issue or add the no-issue label and manually rerun the failed workflow."

        # OPTIONAL: Use the output from the `check-linked-issues` step
            - name: Get the output
              run: echo "How many linked issues? ${{ steps.check-linked-issues.outputs.linked_issues_count }}"
